### PR TITLE
[fix] storage_integration bugs

### LINKED ISSUE #204: Storage integrations cannot have TYPE altered
In code we treat TYPE as an alter-able property:

https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/30ce39a/pkg/resources/storage_integration.go#L239-L242

However, snowflake does not allow TYPE to be altered after creation:

https://docs.snowflake.com/en/sql-reference/sql/alter-storage-integration.html

As a result, our terraform apply failed with the following snowflake error:

```
Error: error updating storage integration: 001420 (22023): SQL compilation error:
invalid property 'TYPE' for 'INTEGRATION - EXTERNAL_STAGE'

  on snowflake_storage_integrations.tf line 10, in resource "snowflake_storage_integration" "s3_storage_integration":
  10: resource "snowflake_storage_integration" "s3_storage_integration" {
```

Also, here was the SQL that got executed, according to the query log:

```sql
ALTER STORAGE INTEGRATION "GCS_STORAGE_INTEGRATION" SET TYPE='EXTERNAL_STAGE'
```

This normally wouldn't be a big problem if it wasn't for the fact that there's another issue which makes terraform always plan to update this value even when there's nothing to change.

### PR DESCRIPTION
**Pull request by ryanking**
Fix bug in handling storage_integration type field.

## Test Plan

* [ ] acceptance tests

* [ ] …

## References
*  Fixes #204

### CODE REVIEW

File: pkg/resources/storage_integration_acceptance_test.go [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+	"testing"
+
+	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest"
+	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
+)
+
+func TestAccStorageIntegration_validation(t *testing.T) {
+	name := acctest.RandStringFromCharSet(10, acctest.CharSetAlpha)
+
+	resource.ParallelTest(t, resource.TestCase{
```
Comment (cziie) [inline pkg/resources/storage_integration_acceptance_test.go:15]: **[tfproviderlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>AT001: missing CheckDestroy

File: pkg/resources/storage_integration_acceptance_test.go [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+				ExpectError: regexp.MustCompile("1 item minimum, config has 0 declared"),
+			},
+		},
+	})
+}
+
+func TestAccStorageIntegration_aws(t *testing.T) {
+	name := acctest.RandStringFromCharSet(10, acctest.CharSetAlpha)
+
+	resource.ParallelTest(t, resource.TestCase{
```
Comment (cziie) [inline pkg/resources/storage_integration_acceptance_test.go:29]: **[tfproviderlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>AT001: missing CheckDestroy

**Review by edulop91 — APPROVED** [review]

**Comment by edulop91** [comment]
fork integration error, but "trusted" success -> merfging
