### PR TITLE
[fix] Verify IAM policy in TestAccSystemGetAWSSNSIAMPolicy_basic

### LINKED ISSUE #439: Acceptance test "TestAccSystemGetAWSSNSIAMPolicy_basic" fail on different Snowflake account
**Provider Version**

The provider version you are using: `0.23.2`

**Terraform Version**

The version of Terraform you were using when the bug was encountered: `0.14`

**Describe the bug**

* Acceptance test `TestAccSystemGetAWSSNSIAMPolicy_basic` fails when I run acceptance test on my Snowflake account.

```
=== CONT  TestAccSystemGetAWSSNSIAMPolicy_basic
    system_get_aws_sns_iam_policy_acceptance_test.go:22: Step 1/1 error: Check failed: Check 2/2 error: data.snowflake_system_get_aws_sns_iam_policy.p: Attribute 'aws_sns_topic_policy_json' expected "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"1\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::494544507972:user/3gmi-s-ssca3411\"},\"Action\":[\"sns:Subscribe\"],\"Resource\":[\"arn:aws:sns:us-east-1:1234567890123456:mytopic\"]}]}", got "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"1\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::532029211228:user/154a-s-sgss5425\"},\"Action\":[\"sns:Subscribe\"],\"Resource\":[\"arn:aws:sns:us-east-1:1234567890123456:mytopic\"]}]}"
--- FAIL: TestAccSystemGetAWSSNSIAMPolicy_basic (18.16s)
FAIL
coverage: 71.4% of statements
FAIL    github.com/chanzuckerberg/terraform-provider-snowflake/pkg/datasources  18.201s
?       github.com/chanzuckerberg/terraform-provider-snowflake/pkg/db   [no test files]
```

* This is because expected IAM User ARN is hard coded in the test code `terraform-provider-snowflake/pkg/datasources/system_get_aws_sns_iam_policy_acceptance_test.go` but actual ARB is generated based on actual Snowflake account.

```
resource.TestCheckResourceAttr("data.snowflake_system_get_aws_sns_iam_policy.p", "aws_sns_topic_policy_json",
    `{"Version":"2012-10-17","Statement":[{"Sid":"1","Effect":"Allow",
    "Principal":{"AWS":"arn:aws:iam::532029211228:user/3gmi-s-ssca3411"},
    "Action":["sns:Subscribe"],"Resource":["arn:aws:sns:us-east-1:1234567890123456:mytopic"]}]}`),
),
```

**Expected behavior**

* All of acceptance test should pass.

**Code samples and commands**

```
make test-acceptance
```

**Additional context**

### PR DESCRIPTION
**Pull request by yohei1126**
* AWS IAM User ARN is different for each Snowflake account but IAM user ARN is hardcoded in an acceptance test.
* This PR makes the AWS IAM User ARN configurable by environment variable.
* Fix #439

## Test Plan

* [x] acceptance tests

* [ ] …

## References

*

### CODE REVIEW

**Comment by yohei1126** [comment]
@ryanking @alldoami Would you review this?

**Review by ryanking — CHANGES_REQUESTED** [review]
I would prefer that we instead rewrite the test to not care at all about the IAM user. I think the assertion could be as simple as "we got some valid JSON".

**Comment by yohei1126** [comment]
@ryanking Changed the test to verify policy JSON using regex. Please review it.

File: pkg/datasources/system_get_aws_sns_iam_policy_acceptance_test.go [hunk 1]
```diff
@@ -17,17 +18,17 @@ func providers() map[string]*schema.Provider {
 }
 
 func TestAccSystemGetAWSSNSIAMPolicy_basic(t *testing.T) {
-	// r := require.New(t)
-
+	// IAM user in the Principal part is unique for each Snowflake account.
+	// This just check it policy json has a valid form.
+	r, _ := regexp.Compile(`\{"Version":"2012\-10\-17","Statement":\[\{"Sid":"1","Effect":"Allow","Principal":\{"AWS":"arn:aws:iam::[0-9]+:user\/[0-9a-zA-Z_\+=,\.@\-]+"\},"Action":\["sns:Subscribe"\],"Resource":\["arn:aws:sns:us\-east\-1:1234567890123456:mytopic"\]\}\]\}`)
```
Comment (ryanking) [inline pkg/datasources/system_get_aws_sns_iam_policy_acceptance_test.go:23]: I think parsing json with a regex like this is too brittle.

**Review by ryanking — CHANGES_REQUESTED** [review]

File: pkg/datasources/system_get_aws_sns_iam_policy_acceptance_test.go (hunk 1 above)
Comment (yohei1126) [reply pkg/datasources/system_get_aws_sns_iam_policy_acceptance_test.go:23]: what do you want? you can suggest

Comment (ryanking) [reply pkg/datasources/system_get_aws_sns_iam_policy_acceptance_test.go:23]: I don't think we can depend much of the content, other than it is a string that contains JSON.

So I think something as simple as `a non-empty` string would be fine.

**Comment by yohei1126** [comment]
@ryanking Can you review this?

**Review by ryanking — APPROVED** [review]
